add long term archive
corona-warn-app/cwa-quick-test-backend pull request #203
Opened 2021-10-20 07:58 UTC by epicsoft-de

2021-10-20 12:21 UTC, mschulte-tsi requested changes

2021-10-20 12:21 UTC, mschulte-tsi commented on src/main/resources/application-cloud.yml
> +      pepper: #### TODO set value
set the value to ${QT_ARCHIVE_PEPPER}

2021-10-20 12:21 UTC, mschulte-tsi commented on src/main/resources/application-cloud.yml
> +        iterations: #### TODO set value
set the value to e.g. ${QT_ARCHIVE_ITERATIONS}

2021-10-21 12:19 UTC, epicsoft-de commented on src/main/java/app/coronawarn/quicktest/config/ArchiveEntityManagerConfig.java
> +    private Properties jpaHibernateProperties() {
changed

2021-10-21 12:27 UTC, mschulte-tsi approved these changes

2022-05-24 06:58 UTC, bergmann-dierk commented on src/main/java/app/coronawarn/quicktest/repository/QuickTestArchiveRepository.java
> +            @Param("updatedAt") LocalDateTime updatedAtBefore, Pageable pageable);
Totally right, removed and renamed

2022-05-24 06:58 UTC, bergmann-dierk commented on src/main/java/app/coronawarn/quicktest/service/ArchiveService.java
> +        this.moveToArchive();
removed

2022-05-24 06:59 UTC, bergmann-dierk commented on src/main/java/app/coronawarn/quicktest/service/HsmKeyProvider.java
> +        // TODO impl
replaced by vault transit engine. keeping the file without todo

2022-05-24 06:59 UTC, f11h approved these changes

2022-05-24 07:07 UTC, f11h requested changes
tbd

2022-06-24 10:48 UTC, f11h approved these changes

2022-06-24 10:54 UTC, merged