feat/added Sample Collection timstamp
corona-warn-app/cwa-quick-test-backend pull request #98
Opened 2021-05-21 08:18 UTC by AnnotationGuyTest

added timestamp for sample collection

2021-05-21 14:46 UTC, ascheibal approved these changes

2021-05-25 13:48 UTC, mschulte-tsi requested changes
Please adapt

2021-05-25 13:48 UTC, mschulte-tsi commented on src/main/java/app/coronawarn/quicktest/model/QuickTestResult.java
> +
please remove

2021-05-25 13:48 UTC, mschulte-tsi commented on src/main/java/app/coronawarn/quicktest/model/QuickTestResult.java
> +
please remove

2021-05-25 13:48 UTC, mschulte-tsi commented on src/main/java/app/coronawarn/quicktest/service/QuickTestService.java
> +                TestResult.FAILED.getValue(), deleteTimestamp.toEpochSecond(ZoneOffset.UTC),
move added code to a new line

2021-05-25 13:48 UTC, mschulte-tsi commented on src/main/java/app/coronawarn/quicktest/service/QuickTestService.java
> +                quicktest.getUpdatedAt().toEpochSecond(ZoneOffset.UTC),
set indention to same level for same method

2021-05-25 13:48 UTC, mschulte-tsi commented on src/main/java/app/coronawarn/quicktest/service/QuickTestService.java
> +                quicktest.getUpdatedAt().toEpochSecond(ZoneOffset.UTC),
set indention to same level for same method

2021-05-25 13:48 UTC, mschulte-tsi commented on src/main/java/app/coronawarn/quicktest/model/QuickTestResult.java
> +
both added newlines

2021-05-25 13:48 UTC, mschulte-tsi commented on src/main/java/app/coronawarn/quicktest/model/QuickTestResult.java
> +
both added newlines

2021-05-25 14:11 UTC, mschulte-tsi approved these changes
LGTM

2021-05-25 14:11 UTC, merged